### ISSUE TITLE
Error when level of subsections more than `inherited_levels`

### ISSUE THREAD

**Issue by JoshuaLampert** [jbirnick/typst-rich-counters#4] opened 2024-11-19 20:38 UTC
I want my theorems etc. to be numbered with `inherited_levels: 1`, but I also want to have more than two levels of subsections. Currently, this fails with `Cannot join integer with integer` in the following line:
https://github.com/jbirnick/typst-rich-counters/blob/d461b663791247dfd928ac01d1edeb1a02d954b1/lib.typ#L94
I have an MWE [here](https://typst.app/project/rDI7RTfc9ViQ2y0s9mRDQy). Any ideas how to fix this?

**Comment by jbirnick** [comment] 2024-11-19 21:05
Thanks for catching this. This is an error that can literally only happen in Typst lol.

The problem is that in Typst all content that you produce is joined together. For the `pop()` operation, I only want the side effect of removing the last element of the array. However, it also _returns_ the element that gets removed. In any other programming language this doesn't matter in this context, it would just throw away the return value because I "don't use it". However, in Typst, the semantics is that it joins it together to the content. So it tries to insert the "thrown away" subsection number into the document lol.

Here is a fix for this; put the number into a variable. Then this variable assignment expression will always return empty content, but we still have the side effect of removing the element.
```typc
while num_parent.len() > inherited_levels { let _ = num_parent.pop() } 
```
Also apply this fix at the other occurrence of `pop()`.

**Comment by jbirnick** [comment] 2024-11-19 21:08
I will make a fix for this ready later, but it will take a 1-3 days to be live on Typst Universe. If you need the correct behavior now, you can copy the `lib.typ` file with the fix applied into your project and import `lib.typ` instead of the package for now.

**Comment by JoshuaLampert** [comment] 2024-11-19 21:09
Ah, yes, makes sense. Thanks for the quick answer, the explanation, and the fix!

**Closed as completed** 2024-11-19 21:32 UTC
Labels: bug

**Comment by jbirnick** [comment] 2024-11-21 22:26
Fix is live on Typst Universe now. (version 0.2.2)
